### ISSUE TITLE
addred line to checklist in pr template

### ISSUE THREAD

**Issue by VentusXu09** [mercury-telemetry/mercury#70]
## Title
New checklist item in PR template

## Description
_If this fixes a bug or resolves an issue, provide a link to that issue. Give a detailed description that answers:_
Added a new requirement to PR template checklist that newly required python modules be included in requirements.txt

## Types of Changes
_Put an `x` in the boxes that apply_

- [ ] Feature (non-breaking change which adds functionality)
- [ ] Bug Fix (non-breaking change that fixes an issue)
- [ ] Breaking Change (feature/fix that causes existing features to not work as expected)
- [ x] Documentation

## Checklist

- [ x] I have read the [contribute]contributing<link> doc
- [x ] Classes, scripts, and environment variables follow existing naming convention
- [x ] Lint and Unit tests pass locally
- [x ] New features on hardware have been tested on a local Raspberry Pi
- [x ] Mention new programs/binaries if any must be installed along with this change
- [x ] Mention new environment variables if any have been added to hardware/env file
- [x ] Test coverage should not drop more than 3%
